# Generated by Django 4.0.4 on 2022-12-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('idInstructor', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de instructor')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre de instructor')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido de instructor')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo de instructor')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de instructor')),
                ('rut', models.CharField(max_length=50, verbose_name='rut de instructor')),
                ('estado', models.CharField(max_length=50, verbose_name='estado de instructor')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('idMaterial', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de material')),
                ('nombreMaterial', models.CharField(max_length=50, verbose_name='Nombre de material')),
                ('descripcionMaterial', models.CharField(max_length=50, verbose_name='Descripcion de material')),
                ('stock', models.IntegerField(verbose_name='Stock de material')),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionInstr',
            fields=[
                ('idPostulacion', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de postulacion')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombre de postulante')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellido de postulante')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo de postulante')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de postulante')),
                ('rut', models.CharField(max_length=50, verbose_name='rut de postulante')),
                ('estado', models.CharField(max_length=50, verbose_name='estado de postulante')),
                ('taller', models.CharField(max_length=50, verbose_name='Nombre de taller')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Breve descripción del taller')),
            ],
        ),
    ]
