# Generated by Django 4.0.4 on 2022-12-23 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_postulacioninstr_estado_taller'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='nomTaller',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nombre de taller'),
        ),
    ]
